package com.Model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		// Composite Primary Key order: sendID,time
		arp.addMapping("chat", "sendID,time", Chat.class);
		arp.addMapping("filetest", "number", Filetest.class);
		arp.addMapping("location", "key", Location.class);
		arp.addMapping("news", "newsID", News.class);
		arp.addMapping("user", "userID", User.class);
	}
}

