package com.Model;

import com.Model.base.BaseChat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Chat extends BaseChat<Chat> {
	public static final Chat dao = new Chat().dao();
}
