package com.Model;

import com.Model.base.BaseLocation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Location extends BaseLocation<Location> {
	//这里写一个dao对象，方便controller里面进行数据库的操作
	public static final Location dao = new Location().dao();
}
