package com.Model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNews<M extends BaseNews<M>> extends Model<M> implements IBean {

	public void setLikeCount(java.lang.Integer likeCount) {
		set("likeCount", likeCount);
	}
	
	public java.lang.Integer getLikeCount() {
		return getInt("likeCount");
	}

	public void setNewsID(java.lang.Long newsID) {
		set("newsID", newsID);
	}
	
	public java.lang.Long getNewsID() {
		return getLong("newsID");
	}

	public void setNewsTitle(java.lang.String newsTitle) {
		set("newsTitle", newsTitle);
	}
	
	public java.lang.String getNewsTitle() {
		return getStr("newsTitle");
	}

	public void setNewsContent(java.lang.String newsContent) {
		set("newsContent", newsContent);
	}
	
	public java.lang.String getNewsContent() {
		return getStr("newsContent");
	}

	public void setCoverImage(byte[] coverImage) {
		set("coverImage", coverImage);
	}
	
	public byte[] getCoverImage() {
		return get("coverImage");
	}

	public void setReadCount(java.lang.Integer readCount) {
		set("readCount", readCount);
	}
	
	public java.lang.Integer getReadCount() {
		return getInt("readCount");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
