package com.Model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUserID(java.lang.String userID) {
		set("userID", userID);
	}
	
	public java.lang.String getUserID() {
		return getStr("userID");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public void setIsAdmin(java.lang.Boolean isAdmin) {
		set("isAdmin", isAdmin);
	}
	
	public java.lang.Boolean getIsAdmin() {
		return get("isAdmin");
	}

}
