package com.Model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChat<M extends BaseChat<M>> extends Model<M> implements IBean {

	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setGetID(java.lang.String getID) {
		set("getID", getID);
	}
	
	public java.lang.String getGetID() {
		return getStr("getID");
	}

	public void setSendID(java.lang.String sendID) {
		set("sendID", sendID);
	}
	
	public java.lang.String getSendID() {
		return getStr("sendID");
	}

	public void setIsLocation(java.lang.Boolean isLocation) {
		set("isLocation", isLocation);
	}
	
	public java.lang.Boolean getIsLocation() {
		return get("isLocation");
	}

}
