package com.Model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFiletest<M extends BaseFiletest<M>> extends Model<M> implements IBean {

	/**
	 * 文件名称

	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 文件名称

	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 文件编号
	 */
	public void setNumber(java.lang.Integer number) {
		set("number", number);
	}
	
	/**
	 * 文件编号
	 */
	public java.lang.Integer getNumber() {
		return getInt("number");
	}

}
